version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: tastetrails-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tastetrails
      POSTGRES_USER: tastetrails_user
      POSTGRES_PASSWORD: tastetrails_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tastetrails-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tastetrails_user -d tastetrails"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: tastetrails-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass redispass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tastetrails-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  tastetrails-network:
    driver: bridge